version: '3.8'

networks:
    spring-cloud-network:
        driver: bridge

services:

    ####################################
    # SPRING BOOT CONFIGURATION SERVER #
    ####################################
    xis-cv-configuration-server:
        container_name: xis-cv-configuration-server
        image: xaviiborra/xis-cv-configuration-server:1.0.0
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ####################################
    # SPRING BOOT EUREKA SERVER #
    ####################################
    xis-cv-eureka-server:
        container_name: xis-cv-eureka-server
        image: xaviiborra/xis-cv-eureka-server:1.0.0
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network
        depends_on:
            - xis-cv-configuration-server
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ####################################
    # SPRING BOOT API GATEWAY #
    ####################################
    xis-cv-gateway:
        container_name: xis-cv-gateway
        image: xaviiborra/xis-cv-gateway:1.0.0
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        depends_on:
            - xis-cv-configuration-server
            - xis-cv-eureka-server
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
