version: '3.8'

networks:
    spring-cloud-network:
        driver: bridge

volumes:
    postgres_data:

services:

    #############
    # KEYCLOACK #
    #############
    xis-cv-keycloak:
        container_name: xis-cv-keycloak
        image: quay.io/keycloak/keycloak:23.0.7
        environment:
            KEYCLOAK_DB: postgres
            KEYCLOAK_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
            KEYCLOAK_DB_USERNAME: keycloak
            KEYCLOAK_DB_PASSWORD: password

            KEYCLOAK_HOSTNAME: localhost
            KEYCLOAK_HOSTNAME_PORT: 8080
            KEYCLOAK_HOSTNAME_STRICT: false
            KEYCLOAK_HOSTNAME_STRICT_HTTPS: false

            KEYCLOAK_LOG_LEVEL: info
            KEYCLOAK_METRICS_ENABLED: true
            KEYCLOAK_HEALTH_ENABLED: true
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        command: start-dev
        depends_on:
            - xis-cv-postgres
        ports:
            - 9000:8080

    ######################
    # KEYCLOACK POSTGRES #
    ######################
    xis-cv-keycloak-postgres:
        container_name: xis-cv-keycloak-postgres
        image: postgres:15
        volumes:
        - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password


    ####################################
    # SPRING BOOT CONFIGURATION SERVER #
    ####################################
    xis-cv-configuration-server:
        container_name: xis-cv-configuration-server
        image: xaviiborra/xis-cv-configuration-server:1.0.0
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ####################################
    # SPRING BOOT EUREKA SERVER #
    ####################################
    xis-cv-eureka-server:
        container_name: xis-cv-eureka-server
        image: xaviiborra/xis-cv-eureka-server:1.0.0
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network
        depends_on:
            - xis-cv-configuration-server
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ####################################
    # SPRING BOOT API GATEWAY #
    ####################################
    xis-cv-gateway:
        container_name: xis-cv-gateway
        image: xaviiborra/xis-cv-gateway:1.0.0
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        depends_on:
            - xis-cv-configuration-server
            - xis-cv-eureka-server
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
