version: '3.8'

networks:
    spring-cloud-network:
        driver: bridge

volumes:
    postgres_data:

services:

    #############
    # KEYCLOACK #
    #############
    xis-cv-keycloak:
        container_name: xis-cv-keycloak
        image: jboss/keycloak:latest
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - PROXY_ADDRESS_FORWARDING=true
            - DB_VENDOR=mysql
            - DB_ADDR=db
            - DB_PORT=3306
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=example
        depends_on:
            - xis-cv-keycloak-mysql
        ports:
            - 8181:8080
            - 9990:9990
        networks:
            - spring-cloud-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ######################
    # KEYCLOACK POSTGRES #
    ######################
    xis-cv-keycloak-mysql:
        container_name: xis-cv-keycloak-postgres
        image: mysql:5
        volumes:
            - ../data-keycloak:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: example
        ports:
            - 3309:3306
        networks:
            - spring-cloud-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s


    ####################################
    # SPRING BOOT CONFIGURATION SERVER #
    ####################################
    xis-cv-configuration-server:
        container_name: xis-cv-configuration-server
        image: xaviiborra/xis-cv-configuration-server:1.0.0
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ####################################
    # SPRING BOOT EUREKA SERVER #
    ####################################
    xis-cv-eureka-server:
        container_name: xis-cv-eureka-server
        image: xaviiborra/xis-cv-eureka-server:1.0.0
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network
        depends_on:
            - xis-cv-configuration-server
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    ####################################
    # SPRING BOOT API GATEWAY #
    ####################################
    xis-cv-gateway:
        container_name: xis-cv-gateway
        image: xaviiborra/xis-cv-gateway:1.0.0
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        depends_on:
            - xis-cv-configuration-server
            - xis-cv-eureka-server
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
